# Generated by Django 4.1.2 on 2023-03-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_text_poll_question_text_vote_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
    ]
